name: Trigger auto deployment for cafe-api

on:
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cafe-api-AutoDeployTrigger-96b1838f-3e92-470d-a960-ed2cb41a83c1.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAFEAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAFEAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAFEAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: CafeOrderSystem.Api/Dockerfile
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CAFEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAFEAPI_REGISTRY_PASSWORD }}
          containerAppName: cafe-api
          resourceGroup: DevOpsTest
          imageToBuild: ghcr.io/${{ env.OWNER }}/cafe-api:${{ github.sha }}
          environmentVariables: >
            ConnectionStrings__DefaultConnection=${{ secrets.CAFEAPI_DB_CONNECTION_STRING }}
            JwtSettings__SecretKey=${{ secrets.CAFEAPI_JWT_SECRET_KEY }}
            Stripe__SecretKey=${{ secrets.CAFEAPI_STRIPE_SECRET_KEY }}
            Stripe__WebhookSecret=${{ secrets.CAFEAPI_STRIPE_WEBHOOK_SECRET }}
            ASPNETCORE_ENVIRONMENT=Production
